### ISSUE TITLE
Variable '$' must be of type 'cssSelectorHelper', but here has type 'JQueryStatic'. Web\Scripts\typings\jquery\jquery.d.ts   3936

### ISSUE THREAD

**Issue by Csini** [vanti1980/dailymenuboard#7]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/2734

**Comment by Csini** [comment]
a Protactor (Selenium & and &&) conflicts with jQuery :(

**Comment by Csini** [comment]
https://codedump.io/share/kQF7Ts1Iu5d/1/how-to-use-jquery-with-angular2

**Comment by vanti1980** [comment]
A link tök jó, csak ugyanúgy egy meglévő csomagot kell módosítani hozzá kézzel és ez nem nagyon tetszik.

**Comment by vanti1980** [comment]
No issue any more as of Angular 2.0.0 (typings are not used any more)
