### ISSUE TITLE
use moment with angular2-moment ?

### ISSUE THREAD

**Issue by Csini** [vanti1980/dailymenuboard#8]
https://github.com/urish/angular2-moment

**Comment by Csini** [comment]
cseleztél a typings mappával... tuti kézzel töröltél belőle :) inkább legyen npm module a moment, mert az ng2-ootstrap már úgy is húzza magával. iupdate-eltem az "inportot" az xpath-tokens -ben

**Comment by vanti1980** [comment]
Nem cseleztem. Most a kis gépen egy typings install-lal kellett kisegíteni, de egyébként csont nélkül ment.

**Comment by vanti1980** [comment]
Nem cseleztem. Most a kis gépen egy typings install-lal kellett kisegíteni, de egyébként csont nélkül ment. De megnézem majd azért az ng2-es csomagot is.

**Comment by vanti1980** [comment]
Az angular2-moment csak pipe-okat ad hozzá, de ugyanazt a sima moment.js-t használja.
Nekünk jelenleg a pipe-okra nincs szükségünk.
xpath-tokens.enum.ts-ben használjuk csak a moment-et.

**Comment by vanti1980** [comment]
as angular2-moment would only be needed if we needed pipes (and we don't need pipes as of now) this issue can be considered as no issue (as of now)
